export const PRODUCTS = [
  {
    id:'1', slug:'bombones-galaxia', cat:'bombones', catName:'Bombones Galaxia', isNew:true, isSale:false,
    name:'Bombones Galaxia', tagline:'Cacao 56% · Colores planetarios · Rellenos artesanales',
    desc:'Una colección de esferas perfectas que imitan los planetas del cosmos. Cada bombón es un mundo distinto con rellenos únicos que explotan en el paladar. Elaborados con cacao de origen y colorantes naturales.',
    story:'Inspirados en los planetas del sistema solar, cada esfera es pintada a mano por el maestro chocolatero.',
    price:9800, oldPrice:null,
    sphere:'radial-gradient(circle at 35% 28%, #FF8C42, #D94F2B 40%, #8B2500 70%, #4A1200)',
    ingredients:['Cacao 56%','Manteca de cacao','Colorantes naturales','Rellenos artesanales'],
    stock:50,
  },
  {
    id:'2', slug:'supernova-de-frutos', cat:'tabletas', catName:'Tabletas Cósmicas', isNew:true, isSale:true,
    name:'Supernova de Frutos', tagline:'56% Cacao · Gel de Maracuyá · Crocante de Coco · Trufa de Frambuesa',
    desc:'La explosión más brillante del universo chocolístico. Tres rellenos distintos que estallan en el paladar como una supernova recién nacida. 56% cacao artesanal con inclusiones de frutos tropicales.',
    story:'Creada para representar la explosión más energética del cosmos: la supernova.',
    price:18900, oldPrice:22000,
    sphere:'radial-gradient(circle at 32% 28%, #FFD700, #FF8C00 30%, #FF4500 55%, #C0392B 75%, #8B0000)',
    ingredients:['Cacao 56%','Gel de maracuyá','Crocante de coco','Trufa de frambuesa','Manteca de cacao'],
    stock:30,
  },
  {
    id:'3', slug:'nebula-volcanica', cat:'bombones', catName:'Bombones Galaxia', isNew:false, isSale:false,
    name:'Nebula Volcánica', tagline:'Frambuesa · Maracuyá · Cacao 72% oscuro',
    desc:'Rojo intenso que encierra una ganache de frambuesa y maracuyá de origen. Inspirada en las nebulosas de gas más densas del universo.',
    story:'El rojo profundo evoca el gas ionizado de una nebulosa joven, llena de energía y vida.',
    price:9800, oldPrice:null,
    sphere:'radial-gradient(circle at 35% 28%, #FF6B6B, #C0392B 35%, #8B0000 65%, #3D0000)',
    ingredients:['Cacao 72%','Frambuesa','Maracuyá','Manteca de cacao'],
    stock:40,
  },
  {
    id:'4', slug:'aurora-boreal', cat:'bombones', catName:'Bombones Galaxia', isNew:false, isSale:false,
    name:'Aurora Boreal', tagline:'Maracuyá · Coco · Cacao blanco 34%',
    desc:'Azul y blanco se fusionan en una danza de luz sobre un fondo de cacao blanco. Como el primer resplandor del amanecer cósmico en los polos.',
    story:'Las auroras boreales son la danza de partículas solares con la atmósfera. Este bombón captura esa magia.',
    price:9800, oldPrice:null,
    sphere:'radial-gradient(circle at 35% 28%, #B0E0FF, #4A90D9 35%, #1B4F8A 65%, #0A2463)',
    ingredients:['Cacao blanco 34%','Maracuyá','Coco','Flor de sal'],
    stock:40,
  },
  {
    id:'5', slug:'marte-especiado', cat:'bombones', catName:'Bombones Galaxia', isNew:false, isSale:false,
    name:'Marte Especiado', tagline:'Canela · Jengibre · Pimienta · Cacao 85%',
    desc:'El planeta rojo capturado en chocolate. Calor especiado que evoluciona como la atmósfera marciana en un atardecer eterno de tonos naranja y rojo.',
    story:'Marte, el planeta guerrero, inspira esta creación intensa y especiada de 85% cacao.',
    price:9800, oldPrice:null,
    sphere:'radial-gradient(circle at 35% 28%, #FF8C42, #D94F2B 38%, #8B2500 68%, #4A1200)',
    ingredients:['Cacao 85%','Canela','Jengibre','Pimienta de cayena'],
    stock:35,
  },
  {
    id:'6', slug:'nebulosa-violeta', cat:'bombones', catName:'Bombones Galaxia', isNew:false, isSale:false,
    name:'Nebulosa Violeta', tagline:'Lavanda · Blueberry · Oro · Cacao 64%',
    desc:'Las nebulosas más hermosas del cosmos son violetas. Captura esa esencia floral y frutal en una esfera con detalles de oro real comestible.',
    story:'La Nebulosa del Cangrejo, de color violeta y azul, inspiró esta creación floral y elegante.',
    price:9800, oldPrice:null,
    sphere:'radial-gradient(circle at 35% 28%, #E8B0FF, #9B59B6 38%, #6A1C8A 65%, #2C0040)',
    ingredients:['Cacao 64%','Lavanda','Blueberry','Oro comestible 24k'],
    stock:35,
  },
  {
    id:'7', slug:'polvo-de-estrellas', cat:'bombones', catName:'Bombones Galaxia', isNew:false, isSale:false,
    name:'Polvo de Estrellas', tagline:'Vainilla Bourbon · Caramelo · Cacao 38% leche',
    desc:'Polvo cósmico atrapado en chocolate blanco con manchas doradas. Caramelo artesanal fluye como corrientes estelares entre la suavidad del chocolate con leche.',
    story:'Cada estrella al morir libera polvo que forma nuevas estrellas. El ciclo eterno del cosmos.',
    price:9800, oldPrice:null,
    sphere:'radial-gradient(circle at 35% 28%, #FFF8DC, #F5DEB3 38%, #D2691E 65%, #8B4513)',
    ingredients:['Cacao 38%','Vainilla Bourbon','Caramelo artesanal','Sal rosa'],
    stock:40,
  },
  {
    id:'8', slug:'caja-galaxia-12', cat:'cajas', catName:'Cajas Atelier', isNew:false, isSale:true,
    name:'Caja Galaxia · 12 Bombones', tagline:'12 bombones · Selección del maestro · Caja negra magnética',
    desc:'Doce universos cuidadosamente seleccionados del Atelier. Presentados en caja magnética negra con detalles dorados. El regalo perfecto para quien merece lo extraordinario.',
    story:'La caja negra representa el espacio profundo, y cada bombón dentro es un planeta esperando ser descubierto.',
    price:34900, oldPrice:42000,
    sphere:'radial-gradient(circle at 35% 28%, #E8B84B, #C8860A 38%, #8B5E0A 65%, #3D2A00)',
    ingredients:['Selección de 12 bombones del Atelier'],
    stock:20,
  },
  {
    id:'9', slug:'eclipse-de-matcha', cat:'edicion', catName:'Edición Limitada', isNew:true, isSale:false,
    name:'Eclipse de Matcha', tagline:'Matcha ceremonial · Cacao blanco · Sésamo negro · Solo 50 unidades',
    desc:'Cuando el sol se oculta y la luna toma su lugar. Matcha ceremonial de primer flush sobre cacao blanco puro con sésamo negro. Edición limitada de solo 50 unidades.',
    story:'El eclipse es el momento más misterioso del cosmos. Esta creación une Oriente y el universo en un solo bocado.',
    price:12900, oldPrice:null,
    sphere:'radial-gradient(circle at 35% 28%, #90EE90, #3CB371 38%, #1B6B3A 65%, #0A3A1A)',
    ingredients:['Cacao blanco 34%','Matcha ceremonial','Sésamo negro','Sal flor'],
    stock:50,
  },
  {
    id:'10', slug:'solsticio-de-whisky', cat:'edicion', catName:'Edición Limitada', isNew:true, isSale:false,
    name:'Solsticio de Whisky', tagline:'Whisky Single Malt 12 años · Cacao 85% · Sal ahumada · 200 unidades',
    desc:'Solo 200 unidades. Una creación que marca el momento exacto del solsticio: cacao de intensidad máxima infusionado con notas ahumadas de whisky Single Malt de 12 años.',
    story:'El solsticio marca el punto de máxima luz o máxima oscuridad. Este chocolate celebra la oscuridad más profunda.',
    price:14900, oldPrice:null,
    sphere:'radial-gradient(circle at 35% 28%, #D4A843, #8B6914 38%, #5C430D 65%, #2A1F06)',
    ingredients:['Cacao 85%','Whisky Single Malt 12 años','Sal ahumada'],
    stock:200,
  },
  {
    id:'11', slug:'caja-atelier-24', cat:'cajas', catName:'Cajas Atelier', isNew:false, isSale:false,
    name:'Caja Atelier · 24 Bombones', tagline:'24 bombones · Colección completa · Presentación premium con libro de cata',
    desc:'La experiencia MAKANGRU completa. Veinticuatro creaciones del Atelier en presentación premium con libro de notas de cata incluido.',
    story:'Para quien quiere descubrir todo el universo MAKANGRU en una sola experiencia.',
    price:62000, oldPrice:75000,
    sphere:'radial-gradient(circle at 35% 28%, #E8C87B, #C8A030 38%, #8B6914 65%, #3D2A00)',
    ingredients:['Selección de 24 bombones del Atelier'],
    stock:15,
  },
  {
    id:'12', slug:'via-lactea', cat:'tabletas', catName:'Tabletas Cósmicas', isNew:false, isSale:false,
    name:'Vía Láctea', tagline:'Caramelo salado · Avellanas Piamonte · Cacao leche 38%',
    desc:'Una tableta que contiene toda la dulzura de la Vía Láctea. El caramelo fluye como corrientes estelares entre avellanas tostadas de Piamonte.',
    story:'La Vía Láctea vista desde la Tierra en una noche sin luna: el horizonte dulce del cosmos.',
    price:15900, oldPrice:null,
    sphere:'radial-gradient(circle at 35% 28%, #C8C8E8, #9090C8 38%, #4040A0 65%, #10105A)',
    ingredients:['Cacao 38%','Caramelo artesanal','Avellanas Piamonte','Sal rosa'],
    stock:25,
  },
]

export const CATEGORIES = [
  { id:'bombones', name:'Bombones Galaxia', icon:'❋', slug:'bombones' },
  { id:'tabletas', name:'Tabletas Cósmicas', icon:'◇', slug:'tabletas' },
  { id:'cajas', name:'Cajas Atelier', icon:'▣', slug:'cajas' },
  { id:'edicion', name:'Edición Limitada', icon:'✧', slug:'edicion' },
]
